import * as webllm from "https://esm.run/@mlc-ai/web-llm";

const $=id=>document.getElementById(id);
const DBKEY="fabien_ai_web_v1";
let engine=null,engineReady=false,engineLoading=false,running=false;
let selectedAgent="coordinator",currentProjectId=null;

const AGENTS={
coordinator:{name:"Chef",icon:"♛",color:"#4ca4ff",role:"Tu es le chef de projet. Tu coordonnes les spécialistes, évites les doublons, synthétises et demandes les validations nécessaires."},
finance:{name:"Finance",icon:"▥",color:"#ffb44b",role:"Tu es analyste financier. Vérifie revenus, coûts, marges, hypothèses, unités et cohérence arithmétique. N'invente aucun chiffre."},
spaces:{name:"Architecture",icon:"◇",color:"#35e9a0",role:"Tu es spécialiste de programmation d'espaces et parcours client. Vérifie surfaces, circulation, capacité et réalisme. Tu ne remplaces pas un architecte ou ingénieur réglementé."},
operations:{name:"Opérations",icon:"⚙",color:"#40d7ee",role:"Tu es responsable opérations. Vérifie horaires, rotations, personnel, nettoyage, capacité, dépendances et goulots d'étranglement."},
clinic:{name:"Clinique",icon:"✚",color:"#ef8fc7",role:"Tu analyses l'organisation clinique: flux, salles, rendez-vous, collaboration et suivi. Tu ne poses aucun diagnostic."},
toladi:{name:"Toladi",icon:"◉",color:"#e4c64f",role:"Tu analyses l'univers de marque, l'expérience, le packaging et l'intégration spatiale."},
marketing:{name:"Marketing",icon:"✦",color:"#f28a67",role:"Tu es spécialiste marketing. Recherche clarté, crédibilité et conversion, sans promesses trompeuses."},
investor:{name:"Investisseur",icon:"▤",color:"#7fa8ed",role:"Tu analyses le projet comme investisseur: chiffres, risques, hypothèses, besoins et questions critiques."},
critic:{name:"Critique",icon:"⌕",color:"#ff5d8a",role:"Tu cherches contradictions, hypothèses fragiles, doubles comptes, oublis, risques et éléments non validés."},
verifier:{name:"Vérification",icon:"✓",color:"#a981ff",role:"Tu consolides les analyses. Distingue FAITS, HYPOTHÈSES, À VÉRIFIER et DÉCISIONS. Ne valide jamais une exigence légale ou réglementaire sans source compétente."}
};
const SPECIALISTS=["finance","spaces","operations","clinic","toladi","marketing","investor"];
const SLOTS={working:[[8,18],[23,25],[12,31]],waiting:[[64,18],[78,23],[70,28]],blocked:[[8,69],[23,73],[13,78]],resting:[[55,68],[67,70],[79,70],[60,79],[72,80],[84,79]]};

const now=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID?.()||Date.now()+"-"+Math.random().toString(16).slice(2);
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const strip=s=>String(s??"").replace(/<think>[\s\S]*?<\/think>/gi,"").replace(/<\/think>/gi,"").replace(/^\s*(Let me|We need|I need|I will)[^\n]*\n+/i,"").trim();
const fmt=iso=>{const d=new Date(iso);return Number.isNaN(d.getTime())?"":d.toLocaleTimeString("fr-CA",{hour:"2-digit",minute:"2-digit"})};

function baseDB(){return {settings:{parallel:2,model:"Qwen2.5-1.5B-Instruct-q4f16_1-MLC"},projects:[{id:"mon-projet",name:"Mon projet",description:"Projet local",memory:"",created_at:now(),runs:[],messages:[],activity:[]}],selectedProject:"mon-projet"}}
function loadDB(){try{return {...baseDB(),...JSON.parse(localStorage.getItem(DBKEY)||"{}")}}catch{return baseDB()}}
let db=loadDB();
const save=()=>localStorage.setItem(DBKEY,JSON.stringify(db));
const project=()=>db.projects.find(p=>p.id===currentProjectId)||db.projects[0];
function showError(m=""){$("error").textContent=m;$("error").classList.toggle("show",!!m)}
function stateRows(){const p=project(),run=p?.runs?.[p.runs.length-1],m={};Object.keys(AGENTS).forEach(a=>m[a]={agent_id:a,status:"resting",task:"",progress:0,output:"",started_at:"",finished_at:"",reason:""});(run?.agents||[]).forEach(r=>m[r.agent_id]={...m[r.agent_id],...r});return m}
function addActivity(text,agent="coordinator"){const p=project();p.activity=p.activity||[];p.activity.push({id:uid(),time:now(),agent,text});p.activity=p.activity.slice(-60);save()}
function addMessage(from,to,body,channel="internal"){const p=project();p.messages=p.messages||[];p.messages.push({id:uid(),from,to,body:strip(body),channel,time:now()});p.messages=p.messages.slice(-300);save()}

function renderProjects(){const w=$("projects");w.innerHTML="";db.projects.forEach(p=>{const b=document.createElement("button");b.className="project"+(p.id===currentProjectId?" active":"");b.innerHTML=`<strong>${esc(p.name)}</strong><div class="tiny">${esc(p.description||"Projet local")}</div>`;b.onclick=()=>selectProject(p.id);w.appendChild(b)})}
function selectProject(id){currentProjectId=id;db.selectedProject=id;save();selectedAgent="coordinator";$("projectTitle").textContent=project().name;renderAll()}
const stateLabel=s=>({working:"Travaille",waiting:"En attente",blocked:"Bloqué",resting:"Se repose",done:"Terminé"})[s]||"Se repose";
function renderRoom(){const rows=stateRows(),groups={working:[],waiting:[],blocked:[],resting:[]};Object.keys(AGENTS).forEach(a=>{let s=rows[a].status||"resting";if(s==="done")s="resting";groups[s]?.push(a)});$("orbs").innerHTML="";let active=0,blocked=0;Object.entries(groups).forEach(([state,list])=>list.forEach((aid,i)=>{if(state==="working")active++;if(state==="blocked")blocked++;const m=AGENTS[aid],pos=SLOTS[state][i%SLOTS[state].length],el=document.createElement("div");el.className=`orbWrap ${state} ${selectedAgent===aid?"selected":""}`;el.style.left=pos[0]+"%";el.style.top=pos[1]+"%";el.style.setProperty("--c",m.color);el.innerHTML=`<div class="orbTrail"></div><div class="orb"></div><div class="orbLabel">${m.icon} ${m.name}</div><div class="orbStatus">${stateLabel(state)}</div>`;el.onclick=()=>{selectedAgent=aid;renderAll()};$("orbs").appendChild(el)}));$("activeCount").textContent=`● ${active} agent${active>1?"s":""} actif${active>1?"s":""}`;$("blockedCount").textContent=`${blocked} blocage${blocked>1?"s":""}`;$("blockedCount").className="chip "+(blocked?"bad":"");$("roomStatus").textContent=active?`${active} agent${active>1?"s":""} en train de travailler`:"Équipe disponible"}
function elapsed(iso){if(!iso)return"Disponible";const s=Math.max(0,Math.floor((Date.now()-new Date(iso))/1000));return s<60?s+" s":Math.floor(s/60)+" min"}
function renderDetail(){const r=stateRows()[selectedAgent],m=AGENTS[selectedAgent],s=r.status||"resting";$("miniOrb").style.setProperty("--selc",m.color);$("agentName").textContent=m.name;$("agentState").textContent=stateLabel(s);$("agentTask").textContent=r.task||"Aucune mission";$("agentSince").textContent=r.started_at?elapsed(r.started_at):"Disponible";$("agentNext").textContent=s==="working"?"Envoyer son résultat au chef":s==="waiting"?"Commencer quand son tour arrive":s==="blocked"?"Résoudre le blocage":"Attend une nouvelle mission";$("agentProgress").style.width=(r.progress||0)+"%";$("agentProgressText").textContent=(r.progress||0)+" %";$("blocker").className="blocker "+(s==="blocked"?"show":"");$("blocker").textContent=s==="blocked"?"⚠ "+(r.reason||"Cet agent est bloqué."):"";$("agentOutput").textContent=r.output||"Cet agent se repose. Tu peux quand même lui parler directement.";$("directTitle").textContent="Parler à "+m.name}
function renderActivity(){const a=(project().activity||[]).slice(-12).reverse();$("activityList").innerHTML=a.length?a.map(x=>`<div class="activity"><time>${fmt(x.time)}</time><div><b>${esc(AGENTS[x.agent]?.name||x.agent)}</b> · ${esc(x.text)}</div></div>`).join(""):'<div class="empty">Aucune activité.</div>'}
function renderChats(){const msgs=project().messages||[],d=msgs.filter(m=>m.channel==="direct"&&(m.from===selectedAgent||m.to===selectedAgent));$("directChat").innerHTML=d.length?d.slice(-30).map(m=>`<div class="msg ${m.from==="user"?"me":"agent"}"><div class="who">${esc(m.from==="user"?"Vous":AGENTS[m.from]?.name||m.from)} · ${fmt(m.time)}</div>${esc(m.body)}</div>`).join(""):'<div class="empty">Écris à cet agent indépendamment de l’équipe.</div>';const i=msgs.filter(m=>m.channel==="internal"&&((m.from===selectedAgent&&m.to==="coordinator")||(m.from==="coordinator"&&m.to===selectedAgent)));$("chiefChat").innerHTML=i.length?i.slice(-30).map(m=>`<div class="msg internal"><div class="who">${esc(AGENTS[m.from]?.name||m.from)} · ${fmt(m.time)}</div>${esc(m.body)}</div>`).join(""):'<div class="empty">Les échanges avec le chef apparaîtront ici.</div>'}
function renderReport(){const r=project().runs||[];$("reportText").textContent=r[r.length-1]?.final_report||"Aucun rapport pour ce projet."}
function renderAll(){renderProjects();renderRoom();renderDetail();renderActivity();renderChats();renderReport()}

async function ensureModel(){if(engineReady&&engine)return true;if(engineLoading)return false;if(!navigator.gpu){showError("WebGPU n’est pas disponible. Utilise Chrome récent sur ce Mac.");return false}engineLoading=true;showError("");$("loadModelBtn").disabled=true;$("engineText").textContent="Chargement de l’IA locale…";const model=$("modelSelect").value;db.settings.model=model;save();try{const appConfig={...webllm.prebuiltAppConfig,cacheBackend:"indexeddb"};engine=await webllm.CreateMLCEngine(model,{appConfig,initProgressCallback:p=>{const pc=Math.round((p.progress||0)*100);$("loadBarFill").style.width=pc+"%";$("loadPct").textContent=pc+" %";$("setupText").textContent=p.text||"Téléchargement du modèle…"}});engineReady=true;$("engineDot").className="statusDot ok";$("engineText").textContent="IA locale prête";$("loadModelBtn").textContent="IA locale prête ✓";$("setupText").textContent="Le modèle est prêt. Les analyses se font dans ce navigateur.";return true}catch(e){$("engineDot").className="statusDot bad";$("engineText").textContent="Erreur IA locale";showError("Impossible de charger le modèle : "+(e?.message||e));return false}finally{engineLoading=false;$("loadModelBtn").disabled=false}}
async function llm(system,user,max_tokens=500){if(!await ensureModel())throw new Error("IA locale non prête");const r=await engine.chat.completions.create({messages:[{role:"system",content:system+"\nRéponds en français. N'affiche jamais ton raisonnement interne. N'invente pas les données manquantes."},{role:"user",content:user}],temperature:.25,max_tokens});return strip(r.choices?.[0]?.message?.content||"")}
const memory=()=>project().memory||"";
function choose(goal){const g=goal.toLowerCase(),o=[],add=a=>{if(!o.includes(a))o.push(a)};if(/reven|coût|cout|budget|marge|prix|rentab|tax|salaire/.test(g))add("finance");if(/plan|surface|pi²|m2|m²|salle|vestiaire|circulation|architect/.test(g))add("spaces");if(/horaire|rotation|capacité|capacite|personnel|nettoyage|opération/.test(g))add("operations");if(/clinique|thérap|client|rendez-vous|soin/.test(g))add("clinic");if(/toladi|huile|packaging|marque|bouteille/.test(g))add("toladi");if(/marketing|instagram|pub|vente|communication/.test(g))add("marketing");if(/invest|business|présentation|financement/.test(g))add("investor");if(o.length<2){add("finance");add("operations")}return o.slice(0,5)}
async function plan(goal){try{const out=await llm(AGENTS.coordinator.role,`MÉMOIRE:\n${memory()||"Aucune"}\n\nMISSION:\n${goal}\n\nChoisis 2 à 5 spécialistes parmi finance, spaces, operations, clinic, toladi, marketing, investor. Réponds: AGENTS: id,id puis PLAN: une phrase.`,180),m=out.match(/AGENTS\s*:\s*([^\n]+)/i),arr=m?m[1].split(/[,; ]+/).filter(x=>SPECIALISTS.includes(x)):[];return {agents:arr.length?[...new Set(arr)].slice(0,5):choose(goal),plan:out}}catch{return {agents:choose(goal),plan:"Plan local de secours."}}}
function makeRun(goal){const run={id:uid(),goal,created_at:now(),status:"running",agents:Object.keys(AGENTS).map(a=>({agent_id:a,status:"resting",task:"",progress:0,output:"",started_at:"",finished_at:"",reason:""})),final_report:""};project().runs.push(run);project().runs=project().runs.slice(-15);save();return run}
const row=(run,a)=>run.agents.find(x=>x.agent_id===a);
function setA(run,a,p){Object.assign(row(run,a),p);save();renderAll()}
async function doAgent(run,aid,goal){setA(run,aid,{status:"working",task:`Analyse : ${goal.slice(0,70)}`,progress:20,started_at:now(),reason:""});addActivity("commence son analyse",aid);addMessage("coordinator",aid,`Analyse cette mission : ${goal}`,"internal");try{const out=await llm(AGENTS[aid].role+`\nSignale les blocages, distingue fait/hypothèse et ne prétends jamais qu'une règle légale est satisfaite sans preuve.`,`MÉMOIRE DU PROJET:\n${memory()||"Aucune donnée"}\n\nMISSION:\n${goal}\n\nFais uniquement ton analyse.`,650);const blocked=/donnée.{0,15}manquant|impossible|bloqu/i.test(out)&&memory().trim().length<40;setA(run,aid,{status:blocked?"blocked":"done",progress:100,output:out,finished_at:now(),reason:blocked?"Informations insuffisantes pour conclure.":""});addMessage(aid,"coordinator",out,"internal");addActivity(blocked?"signale un blocage":"termine son analyse",aid);return out}catch(e){const msg=e?.message||String(e);setA(run,aid,{status:"blocked",progress:100,output:msg,reason:msg,finished_at:now()});return "BLOCAGE "+AGENTS[aid].name+": "+msg}}
async function runMission(){if(running)return;const goal=$("goal").value.trim();if(!goal)return showError("Écris la mission de l’équipe.");running=true;showError("");$("runBtn").disabled=true;$("runBtn").textContent="Équipe en cours…";const run=makeRun(goal);setA(run,"coordinator",{status:"working",task:"Prépare et distribue la mission",progress:20,started_at:now()});addActivity("prépare la mission");try{const p=await plan(goal);setA(run,"coordinator",{status:"done",progress:100,output:p.plan,finished_at:now()});p.agents.forEach(a=>setA(run,a,{status:"waiting",task:"Attend son tour",progress:5}));const results={};for(const a of p.agents)results[a]=await doAgent(run,a,goal);setA(run,"critic",{status:"working",task:"Contrôle les analyses",progress:20,started_at:now()});const pack=Object.entries(results).map(([a,o])=>`### ${AGENTS[a].name}\n${o}`).join("\n\n");const crit=await llm(AGENTS.critic.role,`MISSION:\n${goal}\n\nANALYSES:\n${pack}\n\nContrôle les contradictions et risques.`,500);setA(run,"critic",{status:"done",progress:100,output:crit,finished_at:now()});addMessage("critic","coordinator",crit,"internal");setA(run,"verifier",{status:"working",task:"Consolide le rapport final",progress:25,started_at:now()});const final=await llm(AGENTS.verifier.role,`MISSION:\n${goal}\n\nMÉMOIRE:\n${memory()||"Aucune"}\n\nANALYSES:\n${pack}\n\nCRITIQUE:\n${crit}\n\nRédige un rapport clair avec RÉPONSE, CHIFFRES/HYPOTHÈSES, PROBLÈMES À CORRIGER, DÉCISIONS POUR FABIEN, PROCHAINE ACTION.`,850);setA(run,"verifier",{status:"done",progress:100,output:final,finished_at:now()});addMessage("verifier","coordinator","Rapport final terminé et prêt pour Fabien.","internal");run.final_report=final;run.status="done";save();addActivity("rapport final terminé","verifier");renderAll()}catch(e){run.status="error";run.final_report="Erreur locale : "+(e?.message||e);save();showError(run.final_report);renderAll()}finally{running=false;$("runBtn").disabled=false;$("runBtn").textContent="▶ Lancer l’équipe"}}
async function sendDirect(){const inp=$("directInput"),msg=inp.value.trim();if(!msg)return;inp.value="";addMessage("user",selectedAgent,msg,"direct");renderChats();$("directOnline").textContent="● réfléchit…";try{const recent=(project().messages||[]).filter(m=>m.channel==="direct"&&(m.from===selectedAgent||m.to===selectedAgent)).slice(-8).map(m=>`${m.from==="user"?"Fabien":AGENTS[m.from]?.name||m.from}: ${m.body}`).join("\n"),reply=await llm(AGENTS[selectedAgent].role,`MÉMOIRE:\n${memory()||"Aucune"}\n\nDISCUSSION:\n${recent}\n\nRéponds directement à Fabien.`,420);addMessage(selectedAgent,"user",reply,"direct");renderChats()}catch(e){addMessage(selectedAgent,"user","Erreur locale : "+(e?.message||e),"direct");renderChats()}finally{$("directOnline").textContent="● disponible"}}

$("loadModelBtn").onclick=ensureModel;
$("modelSelect").value=db.settings.model||"Qwen2.5-1.5B-Instruct-q4f16_1-MLC";
$("modelSelect").onchange=()=>{db.settings.model=$("modelSelect").value;save();engine=null;engineReady=false;$("engineDot").className="statusDot";$("engineText").textContent="Modèle à charger";$("loadModelBtn").textContent="Charger l’IA locale"};
$("parallel").value=String(db.settings.parallel||2);
$("parallel").onchange=()=>{db.settings.parallel=Number($("parallel").value);save()};
$("runBtn").onclick=runMission;$("newTaskBtn").onclick=()=>$("goal").focus();
$("memoryBtn").onclick=()=>$("memoryDrawer").classList.toggle("open");
$("saveMemory").onclick=()=>{const t=$("memoryText").value.trim();if(!t)return;project().memory+=(project().memory?"\n\n":"")+t;save();$("memoryText").value="";$("memoryDrawer").classList.remove("open");addActivity("mémoire du projet mise à jour");renderAll()};
$("newProject").onclick=()=>{const name=prompt("Nom du nouveau projet :");if(!name)return;const description=prompt("Petite description :")||"Projet local",id=name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")||uid();db.projects.push({id,name,description,memory:"",created_at:now(),runs:[],messages:[],activity:[]});selectProject(id)};
$("sendDirect").onclick=sendDirect;$("directInput").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();sendDirect()}});
$("talkFocus").onclick=()=>{$("directInput").focus();$("directPanel").scrollIntoView({behavior:"smooth"})};
$("historyFocus").onclick=()=>$("chiefPanel").scrollIntoView({behavior:"smooth"});
$("copyReport").onclick=async()=>{try{await navigator.clipboard.writeText($("reportText").textContent);$("copyReport").textContent="Copié ✓";setTimeout(()=>$("copyReport").textContent="Copier",1200)}catch{}};
$("privacyBtn").onclick=()=>$("privacyModal").classList.remove("hidden");$("closePrivacy").onclick=()=>$("privacyModal").classList.add("hidden");$("privacyModal").onclick=e=>{if(e.target===$("privacyModal"))$("privacyModal").classList.add("hidden")};
$("clearLocal").onclick=()=>{if(confirm("Effacer tous les projets, conversations et rapports locaux ?")){localStorage.removeItem(DBKEY);location.reload()}};

if(!navigator.gpu){$("engineDot").className="statusDot bad";$("engineText").textContent="WebGPU indisponible";$("setupText").textContent="Utilise Chrome récent pour faire tourner l’IA localement."}else $("engineText").textContent="IA locale disponible";
currentProjectId=db.selectedProject&&db.projects.some(p=>p.id===db.selectedProject)?db.selectedProject:db.projects[0].id;$("projectTitle").textContent=project().name;renderAll();setInterval(renderDetail,1000);